# First step of this project is to reproduce Project Tycho's measles report from 1963.
- Dataset: https://www.tycho.pitt.edu/dataset/US.14189004/?utm_source=chatgpt.com
- Article: https://academic.oup.com/ofid/article/5/7/ofy137/5039595

In [3]:
core_columns = [
    "ConditionName",
    "ConditionSNOMED",
    "Admin1ISO",
    "Admin1Name",
    "PeriodStartDate",
    "PeriodEndDate",
    "CountValue",
    "PartOfCumulativeCountSeries",
    "Fatalities"
]

In [4]:
import pandas as pd

measles_df = pd.read_csv('tycho/US.14189004.csv', low_memory=False)[core_columns]
measles_df.head()

,ConditionName,ConditionSNOMED,Admin1ISO,Admin1Name,PeriodStartDate,PeriodEndDate,CountValue,PartOfCumulativeCountSeries,Fatalities
0,Measles,14189004,US-WI,WISCONSIN,1927-11-20,1927-11-26,85,0,0
1,Measles,14189004,US-WI,WISCONSIN,1927-11-27,1927-12-03,120,0,0
2,Measles,14189004,US-WI,WISCONSIN,1927-12-04,1927-12-10,84,0,0
3,Measles,14189004,US-WI,WISCONSIN,1927-12-18,1927-12-24,106,0,0
4,Measles,14189004,US-WI,WISCONSIN,1927-12-25,1927-12-31,39,0,0

In [18]:
measles_df['Year'] = measles_df['PeriodStartDate'].str.split('-').str[0].astype(int)
measles_df['State'] = measles_df['Admin1ISO'].str.split('-').str[1]

In [19]:
measles_df.head()

,ConditionName,ConditionSNOMED,Admin1ISO,Admin1Name,PeriodStartDate,PeriodEndDate,CountValue,PartOfCumulativeCountSeries,Fatalities,Year,State
0,Measles,14189004,US-WI,WISCONSIN,1927-11-20,1927-11-26,85,0,0,1927,WI
1,Measles,14189004,US-WI,WISCONSIN,1927-11-27,1927-12-03,120,0,0,1927,WI
2,Measles,14189004,US-WI,WISCONSIN,1927-12-04,1927-12-10,84,0,0,1927,WI
3,Measles,14189004,US-WI,WISCONSIN,1927-12-18,1927-12-24,106,0,0,1927,WI
4,Measles,14189004,US-WI,WISCONSIN,1927-12-25,1927-12-31,39,0,0,1927,WI

In [ ]:
assert False

In [20]:
plot_measles_df = measles_df[(measles_df['Year'] >= 1960) & (measles_df['Year'] <= 1970)]
plot_measles_df.head()

,ConditionName,ConditionSNOMED,Admin1ISO,Admin1Name,PeriodStartDate,PeriodEndDate,CountValue,PartOfCumulativeCountSeries,Fatalities,Year,State
1592,Measles,14189004,US-WI,WISCONSIN,1960-01-03,1960-01-09,410,0,0,1960,WI
1593,Measles,14189004,US-WI,WISCONSIN,1960-01-10,1960-01-16,663,0,0,1960,WI
1594,Measles,14189004,US-WI,WISCONSIN,1960-01-17,1960-01-23,429,0,0,1960,WI
1595,Measles,14189004,US-WI,WISCONSIN,1960-01-24,1960-01-30,442,0,0,1960,WI
1596,Measles,14189004,US-WI,WISCONSIN,1960-01-31,1960-02-06,414,0,0,1960,WI

In [22]:
import plotly.express as px

fig = px.choropleth(
    plot_measles_df,
    locations="State",
    locationmode="USA-states",
    color="CountValue",
    animation_frame="Year",
    scope="usa",
    color_continuous_scale="Reds",
    range_color=(plot_measles_df["CountValue"].min(), plot_measles_df["CountValue"].max()),
    title="Disease Incidence Over Time"
)

fig.show()