# Let's work on finding the correlation between measles coverage and incidence

### Let's use
- app/data/tycho_measles_control.csv, Tycho Measles
- raw/Vaccination_Coverage_and_Exemptions_among_Kindergartners_20260827.csv

In [ ]:
import pandas as pd

schoolvaxview_df = pd.read_csv('../raw/school_vax_view/schoolvaxview.csv')
schoolvaxview_df.head()

,Vaccine/Exemption,Dose,Geography Type,Geography,School Year,Estimate (%),Population Size,Percent Surveyed,Footnotes,Number of Exemptions,Survey Type
0,MMR,NaN,States,Kansas,2022-23,91.6,35543.0,30.8,†. ‡. §,NaN,Stratified 1-stage cluster sample
1,MMR,NaN,States,Kentucky,2022-23,90.1,54742.0,96.9,>=. ‡. §,NaN,Census
2,MMR,NaN,States,Louisiana,2022-23,92.2,54314.0,100.0,*,NaN,Census
3,MMR,NaN,States,Maine,2022-23,96.8,12403.0,93.9,NaN,NaN,Census
4,MMR,NaN,States,Maryland,2022-23,96.7,59684.0,100.0,*. ‡,NaN,Census

In [2]:
schoolvaxview_df["year"] = (
    schoolvaxview_df["School Year"]
    .str.split("-")
    .str[0]
    .astype(int)
    .add(1)
)

In [3]:
import us


schoolvaxview_df["Geography"] = schoolvaxview_df["Geography"].map(
    lambda x: us.states.lookup(x).abbr if us.states.lookup(x) else None
)


schoolvaxview_df = schoolvaxview_df.rename(columns={'Geography': 'state'})

In [4]:
core_columns = [
    'Vaccine/Exemption',
    'Dose',
    'Geography Type',
    'School Year',
    'Estimate (%)',
    'year',
    'state',
]

schoolvaxview_df = schoolvaxview_df[core_columns]
schoolvaxview_df.head()

  Vaccine/Exemption Dose Geography Type School Year Estimate (%)  year state
0               MMR  NaN         States     2022-23         91.6  2023    KS
1               MMR  NaN         States     2022-23         90.1  2023    KY
2               MMR  NaN         States     2022-23         92.2  2023    LA
3               MMR  NaN         States     2022-23         96.8  2023    ME
4               MMR  NaN         States     2022-23         96.7  2023    MD

In [6]:
measles_schoolvaxview_df = schoolvaxview_df[(schoolvaxview_df['Vaccine/Exemption'] == 'MMR')
                                            & (schoolvaxview_df['Geography Type'] == 'States')]
len(measles_schoolvaxview_df)

868

In [7]:
measles_schoolvaxview_df.head()

  Vaccine/Exemption Dose Geography Type School Year Estimate (%)  year state
0               MMR  NaN         States     2022-23         91.6  2023    KS
1               MMR  NaN         States     2022-23         90.1  2023    KY
2               MMR  NaN         States     2022-23         92.2  2023    LA
3               MMR  NaN         States     2022-23         96.8  2023    ME
4               MMR  NaN         States     2022-23         96.7  2023    MD