# Let's find missing years of measles and mumps cases from CDC
| Disease     | Missing years |
| ----------- | ------------: |
| **Measles** | **2003–2015** |
| **Mumps**   | **2003–2010** |

We will use PDF's files for summaries for each year
- **2003:** https://stacks.cdc.gov/view/cdc/5560/cdc_5560_DS1.pdf
- **2004:** https://stacks.cdc.gov/view/cdc/5557/cdc_5557_DS1.pdf
- **2005:** https://stacks.cdc.gov/view/cdc/5551/cdc_5551_DS1.pdf
- **2006:** https://stacks.cdc.gov/view/cdc/5546/cdc_5546_DS1.pdf
- **2007:** https://stacks.cdc.gov/view/cdc/5547/cdc_5547_DS1.pdf
- **2008:** https://stacks.cdc.gov/view/cdc/5672/cdc_5672_DS1.pdf
- **2009:** https://stacks.cdc.gov/view/cdc/6125/cdc_6125_DS1.pdf
- **2010:** https://stacks.cdc.gov/view/cdc/21266/cdc_21266_DS1.pdf
- **2011:** https://stacks.cdc.gov/view/cdc/21267/cdc_21267_DS1.pdf
- **2012:** https://stacks.cdc.gov/view/cdc/25289/cdc_25289_DS1.pdf
- **2013:** https://stacks.cdc.gov/view/cdc/35110/cdc_35110_DS1.pdf
- **2014:** https://stacks.cdc.gov/view/cdc/41689/cdc_41689_DS1.pdf
- **2015:** https://stacks.cdc.gov/view/cdc/47455/cdc_47455_DS1.pdf

In [1]:
pdf_urls = {
    2003: "https://stacks.cdc.gov/view/cdc/5560/cdc_5560_DS1.pdf",
    2004: "https://stacks.cdc.gov/view/cdc/5557/cdc_5557_DS1.pdf",
    2005: "https://stacks.cdc.gov/view/cdc/5551/cdc_5551_DS1.pdf",
    2006: "https://stacks.cdc.gov/view/cdc/5546/cdc_5546_DS1.pdf",
    2007: "https://stacks.cdc.gov/view/cdc/5547/cdc_5547_DS1.pdf",
    2008: "https://stacks.cdc.gov/view/cdc/5672/cdc_5672_DS1.pdf",
    2009: "https://stacks.cdc.gov/view/cdc/6125/cdc_6125_DS1.pdf",
    2010: "https://stacks.cdc.gov/view/cdc/21266/cdc_21266_DS1.pdf",
    2011: "https://stacks.cdc.gov/view/cdc/21267/cdc_21267_DS1.pdf",
    2012: "https://stacks.cdc.gov/view/cdc/25289/cdc_25289_DS1.pdf",
    2013: "https://stacks.cdc.gov/view/cdc/35110/cdc_35110_DS1.pdf",
    2014: "https://stacks.cdc.gov/view/cdc/41689/cdc_41689_DS1.pdf",
    2015: "https://stacks.cdc.gov/view/cdc/47455/cdc_47455_DS1.pdf",
}

In [2]:
import requests
import pdfplumber
from io import BytesIO

year = 2015
pdf_url = pdf_urls[year]
pdf_url

response = requests.get(pdf_url)
response.raise_for_status()

pdf_bytes = BytesIO(response.content)

with pdfplumber.open(pdf_bytes) as pdf:

    print("Pages:", len(pdf.pages))

    for page_num, page in enumerate(pdf.pages, start=1):

        text = page.extract_text() or ""

        if "measles" in text.lower() or "mumps" in text.lower():

            print(f"\n{'=' * 60}")
            print(f"PAGE {page_num}")
            print("=" * 60)

            # Show lines containing our diseases
            for line in text.splitlines():
                if "measles" in line.lower() or "mumps" in line.lower():
                    print(line)

Pages: 148

============================================================
PAGE 5
============================================================
California serogroup virus diseases Measles
Eastern equine encephalitis virus disease Mumps

============================================================
PAGE 6
============================================================
10140 Measles (rubeola), total Confirmed and unknown OPHSS
10180 Mumps Confirmed, probable, and unknown OPHSS

============================================================
PAGE 23
============================================================
Measles
has been performed on all clinical isolates as part of a project Measles was declared eliminated from the United States in
Institutes of Health, and international partners (5,6). All because measles remains endemic in much of the world,
National Institutes of Health. The Listeria Initiative has aided in recent years, the majority of measles cases (97%) were
the U.S., causing 10 illnesses (7). A measles outbreak is defined as a chain of transmission
mm6514a2 Canada) (6). The majority of measles cases associated with
system died from pneumonia related to an undetected measles
infection. One or two out of 1,000 persons with measles in
org/10.1093/cid/ciw242 This measles case underscores the fact that the disease can cause
Human Services, CDC; 2015. https://www.cdc.gov/listeria/outbreaks/ 1. Papania MJ, Wallace GS, Rota PA, et al. Elimination of endemic measles,

============================================================
PAGE 24
============================================================
postelimination measles epidemiology in the United States, 2009–2014
economic burden of sixteen measles outbreaks on United States public fully vaccinated.
health departments in 2011. Vaccine 2014;32:1311–7. https://doi. Outbreaks of mumps among university settings are known
4. Council of State and Territorial Epidemiologists. Revision of measles,
rubella, and congenital syndrome case classification as part of elimination vaccine-effectiveness for mumps vaccine is 78% for 1-dose
facilitates mumps transmission.
Measles—United States, January 4–April 2, 2015. MMWR Morb Mortal
Wkly Rep 2015;64:373–6. 1. Dayan GH, Quinlisk MP, Parker AA, et al. Recent resurgence of mumps
6. Zipprich J, Winter K, Hacker J, Xia D, Watt J, Harriman K. Measles in the United States. N Engl J Med 2008;358:1580–9. https://doi.
Mortal Wkly Rep 2015;64:153–4. 2. McLean HQ, Fiebelkorn AP, Temte JL, Wallace GS. Prevention of measles,
rubella, congenital rubella syndrome, and mumps, 2013: summary
Mumps [one], Minnesota [three], New Jersey [one], and Ohio [one])
A total of 1,329 mumps cases in the United States were (H1N2) variant viruses (H1N2v) and three with influenza A

============================================================
PAGE 34
============================================================
Measles, total 188 (0.06)
Mumps 1,329 (0.41)

============================================================
PAGE 53
============================================================
Measles Meningococcal disease

============================================================
PAGE 54
============================================================
Measles Meningococcal disease

============================================================
PAGE 55
============================================================
Area Mumps infections Pertussis Plague Psittacosis Total Acute Chronic

============================================================
PAGE 56
============================================================
Area Mumps infections Pertussis Plague Psittacosis Total Acute Chronic

============================================================
PAGE 66
============================================================
Measles, total 108 46 2 4 6 3 5 4 — — — 10 — 188
Mumps 55 28 29 27 71 46 66 150 205 227 184 241 — 1,329

============================================================
PAGE 69
============================================================
Measles, total 26 (0.65) 21 (0.13) 25 (0.06) 38 (0.09) 42 (0.07) 34 (0.03) 2 (0.00) — 188
Mumps — (0.00) 30 (0.19) 67 (0.16) 857 (1.95) 173 (0.27) 158 (0.15) 25 (0.05) 19 1,329

============================================================
PAGE 72
============================================================
Measles, total 95 (0.06) 93 (0.06) — 188
Mumps 737 (0.47) 571 (0.35) 21 1,329

============================================================
PAGE 73
============================================================
Measles, total 2 (0.04) 13 (0.06) 4 (0.01) (0.01) 122 (0.05) 11 36

============================================================
PAGE 74
============================================================
Mumps 1 (0.02) 53 (0.26) 79 (0.18) 604 (0.24) 18 574 1,329

============================================================
PAGE 75
============================================================
Measles, total 52 (0.09) 107 (0.04) 29 188

============================================================
PAGE 76
============================================================
Mumps 55 (0.10) 615 (0.23) 659 1,329

============================================================
PAGE 117
============================================================
MEASLES. Incidence* of reported cases, by year — United States, 1980–2015
Although measles incidence rates declined substantially soon after licensure of a measles vaccine in the United States
in 1963, outbreaks continued to be reported across the country through the 1980s, and a resurgence of measles
number of cases in ensuing years, and a declaration of measles elimination in 2000. Since 1997, the reported annual
incidence has been <1 case per 1 million population, except in 2014, when measles was introduced into several

============================================================
PAGE 119
============================================================
MUMPS. Incidence* of reported cases, by year — United States, 1990–2015
The widespread use of a second dose of mumps vaccine beginning in 1989 was followed by historically low morbidity
until 2006, when the United States experienced the largest mumps outbreak in two decades. The 2006 outbreak of

============================================================
PAGE 141
============================================================
Wormser GP, Dattwyler RJ, Shapiro ED, et al. The clinical assessment, Mumps
anaplasmosis, and babesiosis: clinical practice guidelines by the Infectious Fiebelkorn AP, Lawler J, Curns AT, Brandeburg C, Wallace GS. Mumps
Diseases Society of America. Clin Infect Dis 2006;43:1089–134. https:// postexposure prophylaxis with a third dose of measles-mumps-
Malaria potentially associated with mumps transmission in yeshivas during a
mumps outbreak among highly vaccinated students: Brooklyn, New
Measles Myers KP, Olsen CW, Gray GC. Cases of swine influenza in humans: a
Control and Prevention. Prevention of measles, rubella, congenital rubella
syndrome, and mumps, 2013: summary recommendations of the Advisory
Papania MJ, Wallace GS, Rota PA, et al. Elimination of endemic measles,

In [3]:
assert False

AssertionError:

# Choose single or two page

In [ ]:
import pandas as pd
import pdfplumber
from io import BytesIO

# pd.set_option("display.max_rows", None)

# Page containing both measles and mumps
page_number = 29

table_settings = {
    "vertical_strategy": "text",
    "horizontal_strategy": "text",
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "intersection_tolerance": 3,
}

with pdfplumber.open(BytesIO(response.content)) as pdf:

    # Account for 2-page PDF offset
    pdf_page_number = page_number + 2

    page = pdf.pages[pdf_page_number - 1]

    tables = page.extract_tables(table_settings)

    print(f"PRINTED PAGE {page_number}")
    print("Tables found:", len(tables))

    # Save first extracted table
    df = pd.DataFrame(tables[0])

    display(df.head(10))

In [ ]:
import pandas as pd
import pdfplumber
from io import BytesIO

# pd.set_option("display.max_rows", None)

# Change these to the page numbers you see printed in the PDF
measles_page = 46
mumps_page = 48

page_numbers = {
    "measles": measles_page,
    "mumps": mumps_page
}

table_settings = {
    "vertical_strategy": "text",
    "horizontal_strategy": "text",
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "intersection_tolerance": 3,
}

with pdfplumber.open(BytesIO(response.content)) as pdf:

    for disease, page_number in page_numbers.items():

        # Account for 2-page PDF offset
        pdf_page_number = page_number + 2

        page = pdf.pages[pdf_page_number - 1]

        tables = page.extract_tables(table_settings)

        print(f"\n{'=' * 50}")
        print(f"{disease.upper()} - PRINTED PAGE {page_number}")
        print(f"{'=' * 50}")
        print("Tables found:", len(tables))

        # Save first extracted table
        df = pd.DataFrame(tables[0])

        if disease == "measles":
            df_measles = df.copy()

        elif disease == "mumps":
            df_mumps = df.copy()

        display(df.head(10))

# Multiple extended pages

In [4]:
import pandas as pd
import pdfplumber
from io import BytesIO

# pd.set_option("display.max_rows", None)

page_numbers = {
    "measles": [51, 52],
    "mumps": [53, 54]
}

table_settings = {
    "vertical_strategy": "text",
    "horizontal_strategy": "text",
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "intersection_tolerance": 3,
}

with pdfplumber.open(BytesIO(response.content)) as pdf:

    for disease, pages in page_numbers.items():

        for i, page_number in enumerate(pages, start=1):

            # Account for 2-page PDF offset
            pdf_page_number = page_number + 2

            page = pdf.pages[pdf_page_number - 1]

            tables = page.extract_tables(table_settings)

            print(f"\n{'=' * 50}")
            print(f"{disease.upper()} - PRINTED PAGE {page_number}")
            print(f"{'=' * 50}")
            print("Tables found:", len(tables))

            df = pd.DataFrame(tables[0])

            if disease == "measles":
                if i == 1:
                    df_measles_1 = df.copy()
                else:
                    df_measles_2 = df.copy()

            elif disease == "mumps":
                if i == 1:
                    df_mumps_1 = df.copy()
                else:
                    df_mumps_2 = df.copy()

            display(df.head(10))

==================================================
MEASLES - PRINTED PAGE 51
==================================================
Tables found: 1

,0,1,2,3,4,5,6,7,8,9
0,,,Morbidi,ty a,nd Mortality Weekly R,eport,,,,
1,,,,,,,,,,
2,TABLE 2j. Number of reported c,ases of notifiab,"le diseases,*",by,geographic division,and are,a — United State,s and U.S. ter,"ritories, 201",5
3,,,,,,,,,,
4,,,M,easl,es,,Meningo,coccal disease,,
5,,,,,,,,,,
6,,,,,,All,Serogroups,O,ther Un,kno
7,Area,Malaria,Total Ind,igen,ous Imported ser,ogroups,ACWY Sero,group B sero,groups ser,ogr
8,,,,,,,,,,
9,United States,"1,390",188,162,26,372,120,111,21,120

==================================================
MEASLES - PRINTED PAGE 52
==================================================
Tables found: 1

,0,1,2,3,4,5,6,7,8,9,10,11
0,,,,Morbidi,ty and,Mortality W,eekly Report,,,,,
1,,,,,,,,,,,,
2,TABLE 2j. (Continued),Number of re,port,ed cases of notifiable,disease,"s,* by geog",raphic divisio,n and a,rea — United States a,nd U.S. territ,ori,"es, 2015"
3,,,,,,,,,,,,
4,,,,M,easles,,,,Meningococcal dise,ase,,
5,,,,,,,,,,,,
6,,,,,,,All,Sero,groups,Other,Un,known
7,Area,M,alaria,Total Ind,igenous,Importe,d serogroup,s A,CWY Serogroup B,serogroups,ser,ogroup
8,,,,,,,,,,,,
9,Pacific,,142,119,113,6,94,,25 18,—,,51

==================================================
MUMPS - PRINTED PAGE 53
==================================================
Tables found: 1

,0,1,2,3,4,5,6,7,8
0,,,Morbidi,ty and Mortalit,y Weekly,Report,,,
1,,,,,,,,,
2,TABLE 2k. Number of reported c,ases of notifiab,"le diseases,",* by geographi,c divisio,n and area — Un,ited States and U.,"S. territories,",2015
3,,,,,,,,,
4,,N,ovel,,,,Q,fever,
5,,influ,enza A,,,,,,
6,,v,irus,,,,,,
7,Area,Mumps infe,ctions P,ertussis Pl,ague,Psittacosis,Total A,cute,Chron
8,,,,,,,,,
9,United States,"1,329",7,"20,762",16,4,156,122,34

==================================================
MUMPS - PRINTED PAGE 54
==================================================
Tables found: 1

,0,1,2,3,4,5,6,7,8,9
0,,,,Morbidit,y and Mor,tality Weekly,Report,,,
1,,,,,,,,,,
2,TABLE 2k. (Continued),Number of report,ed cas,es of notifiable d,"iseases,*",by geographi,c division and,area — United State,s and U.S. territori,es
3,,,,,,,,,,
4,,,,Novel,,,,Q,fever,
5,,,i,nfluenza A,,,,,,
6,,,,virus,,,,,,
7,Area,Mump,s,infections Pe,rtussis,Plague,Psittacosis,Total,Acute Chr,on
8,,,,,,,,,,
9,Pacific,46,,—,"5,720",3,—,44,37,7

In [ ]:
assert False

AssertionError:

# Choose single or two page parse table

In [ ]:
# Keep only the columns we need 
case_df = df.iloc[8:85, [0, 2, 3, 9]].copy()

case_df.columns = [
    "state",
    "measles_indigenous",
    "measles_imported",
    "mumps_cases"
]

# Clean state names
case_df["state"] = case_df["state"].astype(str).str.strip()

# Remove blank rows
case_df = case_df[
    case_df["state"] != ""
].copy()

# This is for 2005 - 2014

In [ ]:
# -------------------------
# Measles
# -------------------------

measles_df = df_measles.iloc[6:, [0, 6, 7]].copy()

measles_df.columns = [
    "state",
    "measles_indigenous",
    "measles_imported"
]

measles_df["state"] = measles_df["state"].astype(str).str.strip()

measles_df = measles_df[
    measles_df["state"] != ""
].copy()


# -------------------------
# Mumps
# -------------------------

mumps_df = df_mumps.iloc[7:, [0, 6]].copy()

mumps_df.columns = [
    "state",
    "mumps_cases"
]

mumps_df["state"] = mumps_df["state"].astype(str).str.strip()

mumps_df = mumps_df[
    mumps_df["state"] != ""
].copy()


# -------------------------
# Merge
# -------------------------

case_df = measles_df.merge(
    mumps_df,
    on="state",
    how="outer"
)

case_df.head()

,state,measles_indigenous,measles_imported,mumps_cases
0,"46 MMWR / Published October 14, 20",sease Control and P,rev,NaN
1,48 MMWR / Published October 1,NaN,NaN,s/Centers for
2,Alabama,—,1,2
3,Alaska,—,—,1
4,Arizona,3,—,12

# 2015

In [5]:
# -------------------------
# Measles
# -------------------------

measles_1 = df_measles_1.iloc[9:, [0, 3, 4]].copy()

measles_1.columns = [
    "state",
    "measles_indigenous",
    "measles_imported"
]


measles_2 = df_measles_2.iloc[9:, [0, 4, 5]].copy()

measles_2.columns = [
    "state",
    "measles_indigenous",
    "measles_imported"
]


# Combine both measles pages
measles_df = pd.concat(
    [measles_1, measles_2],
    ignore_index=True
)

measles_df["state"] = measles_df["state"].astype(str).str.strip()

measles_df = measles_df[
    measles_df["state"] != ""
].copy()


# -------------------------
# Mumps
# -------------------------

mumps_1 = df_mumps_1.iloc[9:, [0, 1]].copy()

mumps_1.columns = [
    "state",
    "mumps_cases"
]


mumps_2 = df_mumps_2.iloc[9:, [0, 1]].copy()

mumps_2.columns = [
    "state",
    "mumps_cases"
]


# Combine both mumps pages
mumps_df = pd.concat(
    [mumps_1, mumps_2],
    ignore_index=True
)

mumps_df["state"] = mumps_df["state"].astype(str).str.strip()

mumps_df = mumps_df[
    mumps_df["state"] != ""
].copy()


# -------------------------
# Merge
# -------------------------

case_df = measles_df.merge(
    mumps_df,
    on="state",
    how="outer"
)

case_df.head()

,state,measles_indigenous,measles_imported,mumps_cases
0,* No cases of anthrax; Cri,eria; eas,tern equine,mean-Congo viral he
1,52 MMWR / Publis,US,Departmen,NaN
2,54 MMWR / Publis,NaN,NaN,"hed August 11, 2017, f"
3,Alabama,—,—,1
4,Alaska,—,—,—

In [ ]:
assert False

AssertionError:

In [6]:
regions = [
    "United States",
    "New England",
    "Mid. Atlantic",
    "E.N. Central",
    "W.N. Central",
    "S. Atlantic",
    "E.S. Central",
    "W.S. Central",
    "Mountain",
    "Pacific"
]

territories = [
    "American Samoa",
    "C.N.M.I.",
    "Guam",
    "Puerto Rico",
    "U.S. Virgin Islands"
]

case_df = case_df[
    ~case_df["state"].isin(regions + territories)
].copy()

In [7]:
import numpy as np
import pandas as pd

case_cols = [
    "measles_indigenous",
    "measles_imported",
    "mumps_cases"
]

for col in case_cols:

    # Clean CDC symbols
    case_df[col] = (
        case_df[col]
        .astype(str)
        .str.strip()
        .replace({
            "-": "0",       # No reported cases
            "—": "0",
            "N": np.nan,    # Not notifiable
            "U": np.nan     # Unavailable
        })
    )

    # IMPORTANT: convert strings to numbers
    case_df[col] = pd.to_numeric(
        case_df[col],
        errors="coerce"
    )

In [8]:
case_df["measles_cases"] = (
    case_df["measles_indigenous"]
    + case_df["measles_imported"]
)

In [9]:
ny_rows = case_df[
    case_df["state"].isin([
        "New York (Upstate)",
        "New York City"
    ])
]

ny = pd.DataFrame({
    "state": ["N.Y."],
    "measles_indigenous": [ny_rows["measles_indigenous"].sum()],
    "measles_imported": [ny_rows["measles_imported"].sum()],
    "mumps_cases": [ny_rows["mumps_cases"].sum()],
    "measles_cases": [ny_rows["measles_cases"].sum()]
})

case_df = case_df[
    ~case_df["state"].isin([
        "New York (Upstate)",
        "New York City"
    ])
]

case_df = pd.concat(
    [case_df, ny],
    ignore_index=True
)

In [ ]:
case_df["year"] = year

In [11]:
case_df = case_df[
    [
        "year",
        "state",
        "measles_cases",
        "mumps_cases"
    ]
]

case_df.head(20)

    year                       state  measles_cases  mumps_cases
0   2003  * No cases of anthrax; Cri            NaN          NaN
1   2003            52 MMWR / Publis            NaN          NaN
2   2003            54 MMWR / Publis            NaN          NaN
3   2003                     Alabama            0.0          1.0
4   2003                      Alaska            0.0          0.0
5   2003                     Arizona            7.0          2.0
6   2003                    Arkansas            0.0          7.0
7   2003                  California          109.0         33.0
8   2003                    Colorado            1.0          6.0
9   2003                 Connecticut            0.0          4.0
10  2003                    Delaware            1.0          2.0
11  2003        District of Columbia            3.0          0.0
12  2003               E. N. Central           19.0        528.0
13  2003                     Florida            5.0         10.0
14  2003                     Georgia            1.0          0.0
15  2003      Guanarito viral hemorr            NaN          NaN
16  2003                      Hawaii            0.0          3.0
17  2003                       Idaho            0.0          8.0
18  2003                    Illinois           17.0        430.0
19  2003                     Indiana            0.0          6.0

In [12]:
len(case_df)

62

In [13]:
# state_map = {
#     "Maine": "ME",
#     "N.H.": "NH",
#     "Vt.": "VT",
#     "Mass.": "MA",
#     "R.I.": "RI",
#     "Conn.": "CT",

#     "N.J.": "NJ",
#     "Pa.": "PA",

#     "Ohio": "OH",
#     "Ind.": "IN",
#     "Ill.": "IL",
#     "Mich.": "MI",
#     "Wis.": "WI",

#     "Minn.": "MN",
#     "Iowa": "IA",
#     "Mo.": "MO",
#     "N. Dak.": "ND",
#     "S. Dak.": "SD",
#     "Nebr.": "NE",
#     "Kans.": "KS",

#     "Del.": "DE",
#     "Md.": "MD",
#     "D.C.": "DC",
#     "Va.": "VA",
#     "W. Va.": "WV",
#     "N.C.": "NC",
#     "S.C.": "SC",
#     "Ga.": "GA",
#     "Fla.": "FL",

#     "Ky.": "KY",
#     "Tenn.": "TN",
#     "Ala.": "AL",
#     "Miss.": "MS",

#     "Ark.": "AR",
#     "La.": "LA",
#     "Okla.": "OK",
#     "Tex.": "TX",

#     "Mont.": "MT",
#     "Idaho": "ID",
#     "Wyo.": "WY",
#     "Colo.": "CO",
#     "N. Mex.": "NM",
#     "Ariz.": "AZ",
#     "Utah": "UT",
#     "Nev.": "NV",

#     "Wash.": "WA",
#     "Oreg.": "OR",
#     "Calif.": "CA",
#     "Alaska": "AK",
#     "Hawaii": "HI",

#     # New York after combining NYC + Upstate NY
#     "N.Y.": "NY"
# }

# For 2005 - ????
state_map = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",

    # Combined NY row we create
    "N.Y.": "NY"
}

In [14]:
case_df["state"] = case_df["state"].map(state_map)

In [15]:
case_df[case_df["state"].isna()]

    year state  measles_cases  mumps_cases
0   2003   NaN            NaN          NaN
1   2003   NaN            NaN          NaN
2   2003   NaN            NaN          NaN
12  2003   NaN           19.0        528.0
15  2003   NaN            NaN          NaN
37  2003   NaN            1.0         24.0
45  2003   NaN            NaN          NaN
49  2003   NaN            NaN          NaN
51  2003   NaN            NaN          NaN
59  2003   NaN            NaN          NaN
60  2003   NaN            NaN          NaN

In [16]:
# if any NA above drop
case_df.dropna(subset=['state'], inplace=True)

In [17]:
case_df.head(10)

    year state  measles_cases  mumps_cases
3   2003    AL            0.0          1.0
4   2003    AK            0.0          0.0
5   2003    AZ            7.0          2.0
6   2003    AR            0.0          7.0
7   2003    CA          109.0         33.0
8   2003    CO            1.0          6.0
9   2003    CT            0.0          4.0
10  2003    DE            1.0          2.0
11  2003    DC            3.0          0.0
13  2003    FL            5.0         10.0

In [18]:
import numpy as np

case_cols = [
    "measles_cases",
    "mumps_cases"
]

case_df[case_cols] = case_df[case_cols].replace(0, np.nan)
case_df.head()

   year state  measles_cases  mumps_cases
3  2003    AL            NaN          1.0
4  2003    AK            NaN          NaN
5  2003    AZ            7.0          2.0
6  2003    AR            NaN          7.0
7  2003    CA          109.0         33.0

In [19]:
len(case_df)

51

# We will have to validate manually before saving

In [20]:
assert False

AssertionError:

In [21]:
case_df.to_csv(f"../raw/mmwr/cases_{year}.csv", index=False)

## Once we have all mumps and measles cases for 2003 to 2015 we must drop all mumps cases from **2011 to 2015**
This is to avoid overlaps of cases from this data and project tycho data

In [22]:
import pandas as pd
from pathlib import Path

folder = Path("../raw/mmwr")

mmwr_df = pd.concat(
    [pd.read_csv(file) for file in sorted(folder.glob("*.csv"))],
    ignore_index=True
)

mmwr_df = mmwr_df.sort_values(
    ["year", "state"]
).reset_index(drop=True)

mmwr_df.head()

   year state  measles_cases  mumps_cases
0  2003    AK            NaN          1.0
1  2003    AK            NaN          2.0
2  2003    AK            NaN          1.0
3  2003    AK            NaN          3.0
4  2003    AK            NaN          2.0

In [23]:
len(mmwr_df)

663

In [24]:
import numpy as np

mmwr_df.loc[
    mmwr_df["year"].between(2011, 2015),
    "mumps_cases"
] = np.nan

In [25]:
mmwr_df[
    mmwr_df["year"].between(2011, 2015)
][["year", "state", "mumps_cases"]]

Empty DataFrame
Columns: [year, state, mumps_cases]
Index: []

In [26]:
mmwr_df.to_csv("../app/data/missing_cases.csv", index=False)