# Clean data for latest measles incidience 

Donwload data here: https://zenodo.org/records/11452259?utm_source=chatgpt.com

In [1]:
import pandas as pd

core_columns = [
    'Admin1ISO',
    'PeriodEndDate',
    'PartOfCumulativeCountSeries',
    'CountValue'
]

measles_df = pd.read_csv('../raw/tycho/US.14189004.csv')
measles_df = measles_df[core_columns]
measles_df.head()

/tmp/ipykernel_7503/4280024867.py:10: DtypeWarning: Columns (0: Admin2Name, 1: CityName, 2: PlaceOfAcquisition) have mixed types. Specify dtype option on import or set low_memory=False.
  measles_df = pd.read_csv('../raw/tycho/US.14189004.csv')

  Admin1ISO PeriodEndDate  PartOfCumulativeCountSeries  CountValue
0     US-WI    1927-11-26                            0          85
1     US-WI    1927-12-03                            0         120
2     US-WI    1927-12-10                            0          84
3     US-WI    1927-12-24                            0         106
4     US-WI    1927-12-31                            0          39

In [2]:
len(measles_df)

436932

In [3]:
measles_df = measles_df[measles_df['PartOfCumulativeCountSeries'] == 0]
measles_df['year'] = measles_df['PeriodEndDate'].str.split('-').str[0].astype(int)
measles_df['state'] = measles_df['Admin1ISO'].str.split('-').str[1]
measles_df.head()

  Admin1ISO PeriodEndDate  PartOfCumulativeCountSeries  CountValue  year state
0     US-WI    1927-11-26                            0          85  1927    WI
1     US-WI    1927-12-03                            0         120  1927    WI
2     US-WI    1927-12-10                            0          84  1927    WI
3     US-WI    1927-12-24                            0         106  1927    WI
4     US-WI    1927-12-31                            0          39  1927    WI

In [4]:
measles_df.drop(columns=['Admin1ISO', 'PeriodEndDate', 'PartOfCumulativeCountSeries'], inplace=True)
measles_df.rename(columns={'CountValue': 'cases'}, inplace=True)
measles_df.head()

   cases  year state
0     85  1927    WI
1    120  1927    WI
2     84  1927    WI
3    106  1927    WI
4     39  1927    WI

In [7]:
measles_df.to_csv('../app/data/latest_measles_cases.csv', index=False)